In [1]:
print('Hello World!')

Hello World!


In [2]:
print('hello world'.title())

Hello World


In [ ]:
'hello world'

In [ ]:
'Hi'

In [ ]:
'hello'

#This is a Markdown (press esc->'m'->enter)<br>
$e^{i\pi}+1=0$



In [3]:
import numpy as np


In [3]:
print(np.__version__)

1.18.1


In [24]:
new_array = np.array([1,2,3,4])

In [25]:
new_array.all()

True

In [101]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [102]:
a


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [83]:
a = np.arange(2,6).reshape(2,2)

In [84]:
a

array([[2, 3],
       [4, 5]])

In [106]:
a = np.arange(24).reshape(4,3,2)

In [135]:
a=np.array([[1,2],[3,4]])

In [136]:
b=np.array([[4,3],[2,1]])

In [137]:
b-a


array([[ 3,  1],
       [-1, -3]])

In [138]:
print(np.__version__)#print the numPy version

1.18.1


In [139]:
list_a = [12.23, 13.32, 100, 36.32]

In [140]:
arr_a = np.array(list_a)

In [141]:
arr_a

array([ 12.23,  13.32, 100.  ,  36.32])

Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10

In [147]:
arr = np.arange(2,11).reshape(3,3)

In [148]:
arr

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

Write a NumPy program to create a **null** vector of size 10 and update sixth value to 11

In [10]:
a = np.zeros(10)
a[6] = 11

In [12]:
a


array([ 0.,  0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.])

Write a NumPy program to create an array with values ranging from 12 to 38

In [13]:
arr = np.arange(12,39)

In [14]:
arr

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37, 38])

Write a NumPy program to reverse an array (first element becomes last)


In [77]:
arr = np.array(range(10))

In [40]:
reverse = arr[::-1]

In [41]:
reverse

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

list[<.start>:<.stop>:<.step>]<br>
So, when you do a[::-1], it starts from the end towards the first taking each element. So it reverses a. 
<br>This is applicable for lists/tuples as well.

Write a NumPy program to convert an array to a float type.


In [84]:
arr = np.asfarray(arr)
# arr = arr.astype(float) or use this option
arr

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [45]:
arr = np.arange(0,9).reshape(3,3)

In [46]:
arr


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [47]:
arr[1,2]

5

Write a NumPy program to create a 2d array with 1 on the border and 0 inside.


In [5]:
arr = np.ones((5,5))
arr = arr.astype(int)
arr

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [6]:
arr[1:-1,1:-1] = 0

In [89]:
arr

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [90]:
help(np.pad)

Help on function pad in module numpy:

pad(array, pad_width, mode='constant', **kwargs)
    Pad an array.
    
    Parameters
    ----------
    array : array_like of rank N
        The array to pad.
    pad_width : {sequence, array_like, int}
        Number of values padded to the edges of each axis.
        ((before_1, after_1), ... (before_N, after_N)) unique pad widths
        for each axis.
        ((before, after),) yields same before and after pad for each axis.
        (pad,) or int is a shortcut for before = after = pad width for all
        axes.
    mode : str or function, optional
        One of the following string values or a user supplied function.
    
        'constant' (default)
            Pads with a constant value.
        'edge'
            Pads with the edge values of array.
        'linear_ramp'
            Pads with the linear ramp between end_value and the
            array edge value.
        'maximum'
            Pads with the maximum value of all or part of

Write a NumPy program to add a border (filled with 0's) around an existing array.



In [7]:
np.pad(arr,(1))

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 1, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 1, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0]])

Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.



In [58]:
a = np.zeros((8,8), dtype = 'int')

In [59]:
a[1::2, ::2] = 1
a[::2, 1::2] = 1
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

Write a NumPy program to create an empty and a full array.



In [70]:
np.empty((3,3)).astype(int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [75]:
np.full((3,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

### for more exercises in NumPy check:
https://www.w3resource.com/python-exercises/numpy/index.php